name: Publish Docker Image

on:
  push:
    # Publish semver tags as releases.
    tags: [ '[0-9]+.[0-9]+.[0-9]+*' ]

jobs:
  build-and-push:
    name: Build and push ${{ matrix.app }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        app: [ service, job ]
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'true'

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.25.0

      - name: Generate API
        run: go tool buf generate

      - name: Generate
        run: go generate ./...

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          flavor: "latest=false"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push eb-${{ matrix.app }}
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/eb-${{ matrix.app }}:${{ steps.meta.outputs.version }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            VERSION=${{ steps.meta.outputs.version }}
            APP_NAME=${{ matrix.app }}
          cache-from: type=gha
          cache-to: type=gha,mode=max